[[redirects]]
  from = "/quote/_f_ah-v-vt"
  to = "https://thegoodland.io/quotes/_f_ah-v-vt/as-we-embark-upon"
  force = true

[[redirects]]
  from = "/quote/_nmanmg2fq"
  to = "https://thegoodland.io/quotes/_nmanmg2fq/every-man-is-as-holy-as-he"
  force = true

[[redirects]]
  from = "/quote/-1dc6dxhrn"
  to = "https://thegoodland.io/quotes/-1dc6dxhrn/how-good-it-is-to-have-the"
  force = true

[[redirects]]
  from = "/quote/-ffvp4d240"
  to = "https://thegoodland.io/quotes/-ffvp4d240/you-yourself-may-ebb-and"
  force = true

[[redirects]]
  from = "/quote/-sqfv1lc1h"
  to = "https://thegoodland.io/quotes/-sqfv1lc1h/a-pastor-in-india-once-told"
  force = true

[[redirects]]
  from = "/quote/-vu_wnjtcs"
  to = "https://thegoodland.io/quotes/-vu_wnjtcs/it-is-the-faith-that"
  force = true

[[redirects]]
  from = "/quote/0ga1zdundj"
  to = "https://thegoodland.io/quotes/0ga1zdundj/this-is-definitely-not-the"
  force = true

[[redirects]]
  from = "/quote/0obivst053"
  to = "https://thegoodland.io/quotes/0obivst053/right-now-we-are-in-an-age"
  force = true

[[redirects]]
  from = "/quote/17gyqh_fb4"
  to = "https://thegoodland.io/quotes/17gyqh_fb4/to-get-his-best-we-must-give"
  force = true

[[redirects]]
  from = "/quote/3i_np308tc"
  to = "https://thegoodland.io/quotes/3i_np308tc/for-we-walk-by-faith-not"
  force = true

[[redirects]]
  from = "/quote/3xy_amw3yh"
  to = "https://thegoodland.io/quotes/3xy_amw3yh/there-is-no-proof-of-the"
  force = true

[[redirects]]
  from = "/quote/4l0u6itijp"
  to = "https://thegoodland.io/quotes/4l0u6itijp/my-giving-of-myself-to-the"
  force = true

[[redirects]]
  from = "/quote/4s4ybxibd3"
  to = "https://thegoodland.io/quotes/4s4ybxibd3/in-our-desire-after-god-let"
  force = true

[[redirects]]
  from = "/quote/5wc7rnc88q"
  to = "https://thegoodland.io/quotes/5wc7rnc88q/go-forth-o-ye-daughters-of"
  force = true

[[redirects]]
  from = "/quote/6nvrwnpagv"
  to = "https://thegoodland.io/quotes/6nvrwnpagv/he-whose-life-is-one-even"
  force = true

[[redirects]]
  from = "/quote/6yp0jbk4ci"
  to = "https://thegoodland.io/quotes/6yp0jbk4ci/as-sorrowful-yet-always"
  force = true

[[redirects]]
  from = "/quote/78mcg8aofp"
  to = "https://thegoodland.io/quotes/78mcg8aofp/we-are-often-hindered-from"
  force = true

[[redirects]]
  from = "/quote/7hskpyqols"
  to = "https://thegoodland.io/quotes/7hskpyqols/we-must-learn-of-jesus-how"
  force = true

[[redirects]]
  from = "/quote/7tx45b1t7r"
  to = "https://thegoodland.io/quotes/7tx45b1t7r/looking-unto-jesus-to"
  force = true

[[redirects]]
  from = "/quote/8-xftuiqea"
  to = "https://thegoodland.io/quotes/8-xftuiqea/are-not-they-careless-of"
  force = true

[[redirects]]
  from = "/quote/82hppyyaaz"
  to = "https://thegoodland.io/quotes/82hppyyaaz/christs-call-to-the-soul-is"
  force = true

[[redirects]]
  from = "/quote/894saixyft"
  to = "https://thegoodland.io/quotes/894saixyft/the-command-is-clear-humble"
  force = true

[[redirects]]
  from = "/quote/8kup2_pnvb"
  to = "https://thegoodland.io/quotes/8kup2_pnvb/god-i-saw-demanded-my"
  force = true

[[redirects]]
  from = "/quote/8rm4w0csmi"
  to = "https://thegoodland.io/quotes/8rm4w0csmi/the-secret-and-reality-of-a"
  force = true

[[redirects]]
  from = "/quote/8rs_tbprbg"
  to = "https://thegoodland.io/quotes/8rs_tbprbg/then-jesus-spoke-to-them"
  force = true

[[redirects]]
  from = "/quote/8xog3eo49r"
  to = "https://thegoodland.io/quotes/8xog3eo49r/did-you-ever-think-of-the"
  force = true

[[redirects]]
  from = "/quote/9_0icyt2lu"
  to = "https://thegoodland.io/quotes/9_0icyt2lu/how-many-of-us-know-that"
  force = true

[[redirects]]
  from = "/quote/asvqydc5b1"
  to = "https://thegoodland.io/quotes/asvqydc5b1/you-probably-know-the"
  force = true

[[redirects]]
  from = "/quote/awtglr2kye"
  to = "https://thegoodland.io/quotes/awtglr2kye/the-blessings-he-bestows-are"
  force = true

[[redirects]]
  from = "/quote/cdfuliagj-"
  to = "https://thegoodland.io/quotes/cdfuliagj-/we-must-be-so-completely"
  force = true

[[redirects]]
  from = "/quote/cibaivlw_t"
  to = "https://thegoodland.io/quotes/cibaivlw_t/just-so-much-as-the-world"
  force = true

[[redirects]]
  from = "/quote/cjoqjyghsw"
  to = "https://thegoodland.io/quotes/cjoqjyghsw/is-the-living-person-now-in"
  force = true

[[redirects]]
  from = "/quote/dc-odmfexj"
  to = "https://thegoodland.io/quotes/dc-odmfexj/sometimes-i-consider-myself"
  force = true

[[redirects]]
  from = "/quote/dcphqpwohe"
  to = "https://thegoodland.io/quotes/dcphqpwohe/looking-unto-jesusand-not"
  force = true

[[redirects]]
  from = "/quote/dsrrkypwfi"
  to = "https://thegoodland.io/quotes/dsrrkypwfi/let-us-get-it-crystal-clear"
  force = true

[[redirects]]
  from = "/quote/dyzkajxhjs"
  to = "https://thegoodland.io/quotes/dyzkajxhjs/do-not-let-us-be-in-a-hurry"
  force = true

[[redirects]]
  from = "/quote/eksrycltau"
  to = "https://thegoodland.io/quotes/eksrycltau/holiness-is-the-very-nature"
  force = true

[[redirects]]
  from = "/quote/el3uao3p6q"
  to = "https://thegoodland.io/quotes/el3uao3p6q/the-whole-christian-life"
  force = true

[[redirects]]
  from = "/quote/ftx3tgtprp"
  to = "https://thegoodland.io/quotes/ftx3tgtprp/i-have-a-pen-in-my-pocket"
  force = true

[[redirects]]
  from = "/quote/fywizob3rm"
  to = "https://thegoodland.io/quotes/fywizob3rm/god-is-god-if-he-is-god-he"
  force = true

[[redirects]]
  from = "/quote/g46brxvt6i"
  to = "https://thegoodland.io/quotes/g46brxvt6i/the-most-excellent-subject"
  force = true

[[redirects]]
  from = "/quote/gbeyq7pgb0"
  to = "https://thegoodland.io/quotes/gbeyq7pgb0/god-never-uses-a-person"
  force = true

[[redirects]]
  from = "/quote/hp3xwyqbe5"
  to = "https://thegoodland.io/quotes/hp3xwyqbe5/oh-how-should-all-hearts-be"
  force = true

[[redirects]]
  from = "/quote/htzqlm7yjp"
  to = "https://thegoodland.io/quotes/htzqlm7yjp/the-world-has-yet-to-see"
  force = true

[[redirects]]
  from = "/quote/hv-zojoeuc"
  to = "https://thegoodland.io/quotes/hv-zojoeuc/plenty-of-experiences"
  force = true

[[redirects]]
  from = "/quote/hzcpcrprzt"
  to = "https://thegoodland.io/quotes/hzcpcrprzt/the-idea-of-cultivation-and"
  force = true

[[redirects]]
  from = "/quote/ifp2uyhf0o"
  to = "https://thegoodland.io/quotes/ifp2uyhf0o/this-mystery-of-union-is"
  force = true

[[redirects]]
  from = "/quote/ihzjsewgxu"
  to = "https://thegoodland.io/quotes/ihzjsewgxu/the-bible-is-a-supernatural"
  force = true

[[redirects]]
  from = "/quote/isjbhc-3x2"
  to = "https://thegoodland.io/quotes/isjbhc-3x2/some-things-may-be-neglected"
  force = true

[[redirects]]
  from = "/quote/iz33lw7uoi"
  to = "https://thegoodland.io/quotes/iz33lw7uoi/if-we-give-ourselves"
  force = true

[[redirects]]
  from = "/quote/j-xrrjpzim"
  to = "https://thegoodland.io/quotes/j-xrrjpzim/we-are-to-live-the-life-of"
  force = true

[[redirects]]
  from = "/quote/j5_orbwq37"
  to = "https://thegoodland.io/quotes/j5_orbwq37/we-all-know-the-value-of"
  force = true

[[redirects]]
  from = "/quote/jt4penbbp8"
  to = "https://thegoodland.io/quotes/jt4penbbp8/before-we-were-saved"
  force = true

[[redirects]]
  from = "/quote/kjqeqtc1_f"
  to = "https://thegoodland.io/quotes/kjqeqtc1_f/to-be-a-living-sacrifice"
  force = true

[[redirects]]
  from = "/quote/komovihs7n"
  to = "https://thegoodland.io/quotes/komovihs7n/looking-unto-jesusto-go"
  force = true

[[redirects]]
  from = "/quote/kswnvrciat"
  to = "https://thegoodland.io/quotes/kswnvrciat/o-when-a-soul-comes-to-know"
  force = true

[[redirects]]
  from = "/quote/llfyjrmfik"
  to = "https://thegoodland.io/quotes/llfyjrmfik/in-the-way-of-thy-judgments"
  force = true

[[redirects]]
  from = "/quote/m921i71h67"
  to = "https://thegoodland.io/quotes/m921i71h67/this-absolute-surrender-to"
  force = true

[[redirects]]
  from = "/quote/mnzl-3cej_"
  to = "https://thegoodland.io/quotes/mnzl-3cej_/in-this-knowledge-of-christ"
  force = true

[[redirects]]
  from = "/quote/mrkjj2ilh8"
  to = "https://thegoodland.io/quotes/mrkjj2ilh8/some-may-give-a-glance-at"
  force = true

[[redirects]]
  from = "/quote/mssujmojlj"
  to = "https://thegoodland.io/quotes/mssujmojlj/though-in-fact-i-am-in"
  force = true

[[redirects]]
  from = "/quote/mtwtvyooup"
  to = "https://thegoodland.io/quotes/mtwtvyooup/dear-christian-do-you-not"
  force = true

[[redirects]]
  from = "/quote/n1f7uaiayu"
  to = "https://thegoodland.io/quotes/n1f7uaiayu/of-what-value-to-christ-is"
  force = true

[[redirects]]
  from = "/quote/n9np6hjhpw"
  to = "https://thegoodland.io/quotes/n9np6hjhpw/when-he-says-abide-in-me"
  force = true

[[redirects]]
  from = "/quote/nez_wtcarh"
  to = "https://thegoodland.io/quotes/nez_wtcarh/o-turn-your-thoughts-from"
  force = true

[[redirects]]
  from = "/quote/ni2jhy5khs"
  to = "https://thegoodland.io/quotes/ni2jhy5khs/the-savour-of-the-good"
  force = true

[[redirects]]
  from = "/quote/oopcdubdqw"
  to = "https://thegoodland.io/quotes/oopcdubdqw/there-is-nothing-smart-about"
  force = true

[[redirects]]
  from = "/quote/qb114mnfdv"
  to = "https://thegoodland.io/quotes/qb114mnfdv/god-hath-sent-forth-the"
  force = true

[[redirects]]
  from = "/quote/qpvl2o31ec"
  to = "https://thegoodland.io/quotes/qpvl2o31ec/we-have-our-life-from-and-in"
  force = true

[[redirects]]
  from = "/quote/qqkt-oobjd"
  to = "https://thegoodland.io/quotes/qqkt-oobjd/must-not-everything-first"
  force = true

[[redirects]]
  from = "/quote/qqx7lygtzs"
  to = "https://thegoodland.io/quotes/qqx7lygtzs/god-is-seeking-that-we"
  force = true

[[redirects]]
  from = "/quote/r72rerpw8i"
  to = "https://thegoodland.io/quotes/r72rerpw8i/i-began-to-realize-the-truth"
  force = true

[[redirects]]
  from = "/quote/rdwrzncowg"
  to = "https://thegoodland.io/quotes/rdwrzncowg/mankind-needs-love-that-was"
  force = true

[[redirects]]
  from = "/quote/rshi6uosli"
  to = "https://thegoodland.io/quotes/rshi6uosli/when-christ-our-life"
  force = true

[[redirects]]
  from = "/quote/rsx1azdq7c"
  to = "https://thegoodland.io/quotes/rsx1azdq7c/come-let-the-proud-man"
  force = true

[[redirects]]
  from = "/quote/sdmh3rljl4"
  to = "https://thegoodland.io/quotes/sdmh3rljl4/with-a-heart-full-of-joy-no"
  force = true

[[redirects]]
  from = "/quote/selfxop-og"
  to = "https://thegoodland.io/quotes/selfxop-og/the-life-god-bestows-is"
  force = true

[[redirects]]
  from = "/quote/sodl8d9cqh"
  to = "https://thegoodland.io/quotes/sodl8d9cqh/he-who-grows-in-grace"
  force = true

[[redirects]]
  from = "/quote/sq8pio3z5y"
  to = "https://thegoodland.io/quotes/sq8pio3z5y/be-more-and-better"
  force = true

[[redirects]]
  from = "/quote/ssobbdffuf"
  to = "https://thegoodland.io/quotes/ssobbdffuf/see-what-a-work-the-lord"
  force = true

[[redirects]]
  from = "/quote/stre3u6jtd"
  to = "https://thegoodland.io/quotes/stre3u6jtd/jesus-christ-gave-himself"
  force = true

[[redirects]]
  from = "/quote/t4rvjvf8e6"
  to = "https://thegoodland.io/quotes/t4rvjvf8e6/put-away-every-un-christian"
  force = true

[[redirects]]
  from = "/quote/t63ok_efah"
  to = "https://thegoodland.io/quotes/t63ok_efah/prayer-is-friendship-with"
  force = true

[[redirects]]
  from = "/quote/tkdavadiuv"
  to = "https://thegoodland.io/quotes/tkdavadiuv/to-deliver-the-soul-from"
  force = true

[[redirects]]
  from = "/quote/tx8mtor9x1"
  to = "https://thegoodland.io/quotes/tx8mtor9x1/there-are-few-things-in"
  force = true

[[redirects]]
  from = "/quote/ue9xa4o_wa"
  to = "https://thegoodland.io/quotes/ue9xa4o_wa/i-was-greatly-impressed-by"
  force = true

[[redirects]]
  from = "/quote/ug2bltw5cy"
  to = "https://thegoodland.io/quotes/ug2bltw5cy/god-wished-to-reveal-himself"
  force = true

[[redirects]]
  from = "/quote/uhamzq4syd"
  to = "https://thegoodland.io/quotes/uhamzq4syd/the-life-we-live-is-the-life"
  force = true

[[redirects]]
  from = "/quote/uvvhljv7wy"
  to = "https://thegoodland.io/quotes/uvvhljv7wy/even-in-the-regenerate-man"
  force = true

[[redirects]]
  from = "/quote/v6kq7tlsce"
  to = "https://thegoodland.io/quotes/v6kq7tlsce/if-you-look-at-the-world"
  force = true

[[redirects]]
  from = "/quote/vhybnd7tdz"
  to = "https://thegoodland.io/quotes/vhybnd7tdz/worrying-is-carrying"
  force = true

[[redirects]]
  from = "/quote/wi1xhf_qju"
  to = "https://thegoodland.io/quotes/wi1xhf_qju/god-will-not-give-me"
  force = true

[[redirects]]
  from = "/quote/wyfsh1plw3"
  to = "https://thegoodland.io/quotes/wyfsh1plw3/god-as-creator-formed-man"
  force = true

[[redirects]]
  from = "/quote/yjlb1mdjoe"
  to = "https://thegoodland.io/quotes/yjlb1mdjoe/i-do-not-pray-that-you-may"
  force = true

[[redirects]]
  from = "/quote/yrxprnha7o"
  to = "https://thegoodland.io/quotes/yrxprnha7o/a-little-while-and-we-are-in"
  force = true

[[redirects]]
  from = "/quote/z2c6hablnk"
  to = "https://thegoodland.io/quotes/z2c6hablnk/it-would-seem-that-our-lord"
  force = true

[[redirects]]
  from = "/quote/zahh-xnbzx"
  to = "https://thegoodland.io/quotes/zahh-xnbzx/gods-end-is-christ-so-also"
  force = true

[[redirects]]
  from = "/quote/zdgn6yyxt4"
  to = "https://thegoodland.io/quotes/zdgn6yyxt4/surely-if-there-is-that"
  force = true

[[redirects]]
  from = "/quote/zmbsdpkcab"
  to = "https://thegoodland.io/quotes/zmbsdpkcab/if-once-we-learn-that-to-be"
  force = true
