backend:
  name: git-gateway
  branch: main
  repo: PatrickMcGrath29/quotes
  squash_merges: true
  use_graphql: true

site_url: https://quotes.thegoodland.io
display_url: https://quotes.thegoodland.io

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: "quote"
    label: "Quote"
    folder: "content/quotes"
    format: "frontmatter"
    create: true
    slug: "{{uuid}}"
    summary: "{{text}}"
    editor:
      preview: false
    identifier_field: uuid
    fields:
      - { label: "Unique ID", name: "uuid", widget: uuid }
      - { label: "Text", name: "text", widget: "text" }
      - {
          label: "Reference",
          name: "reference",
          widget: "relation",
          collection: "references",
          search_fields: ["reference_name", "author_name"],
          value_field: "uuid",
          display_fields: ["reference_name", "author_name"],
          required: false,
        }
      - label: "Categories"
        name: "categories"
        widget: "list"
        field:
          {
            label: "Category",
            name: "categories",
            widget: "relation",
            collection: "categories",
            search_fields: ["name"],
            value_field: "name",
            display_fields: ["name"],
            required: false,
          }
  - name: "categories"
    label: "Categories"
    folder: "content/categories"
    format: "frontmatter"
    create: true
    slug: "{{name}}-{{uuid}}"
    identifier_field: uuid
    summary: "{{name}}"
    editor:
      preview: false
    fields:
      - { label: "Unique ID", name: "uuid", widget: uuid }
      - { label: "Category Name", name: "name", widget: "string" }
  - name: "references"
    label: "References"
    folder: "content/references"
    format: "frontmatter"
    create: true
    slug: "{{uuid}}-{{reference_name}}-{{author_name}}"
    summary: "{{reference_name}} by {{author_name}}"
    editor:
      preview: false
    fields:
      - { label: "Unique ID", name: "uuid", widget: uuid }
      - {
          label: "Reference Name",
          name: "reference_name",
          widget: "string",
          required: false,
        }
      - {
          label: "Author Name",
          name: "author_name",
          widget: "string",
          required: false,
        }
      - { label: "Link", name: "link", widget: "string", required: false }
      - {
          label: "File",
          name: "file",
          widget: "file",
          media_folder: "/public/uploads/references",
          required: false,
        }

local_backend: true
